//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneSite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public string image_link { get; set; }
        public string image_description { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<int> author { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
