//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneSite.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ac216team05dbEntities1 : DbContext
    {
        public ac216team05dbEntities1()
            : base("name=ac216team05dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Article> Articles { get; set; }
        public DbSet<Drone> Drones { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Order_Address> Order_Address { get; set; }
        public DbSet<Order_Line> Order_Line { get; set; }
        public DbSet<Person> People { get; set; }
    }
}
