//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneSite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drone
    {
        public Drone()
        {
            this.Order_Line = new HashSet<Order_Line>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image_link { get; set; }
        public string image_description { get; set; }
        public int stock { get; set; }
        public string size { get; set; }
        public double weight { get; set; }
        public double battery_life { get; set; }
        public double range { get; set; }
        public double price { get; set; }
    
        public virtual ICollection<Order_Line> Order_Line { get; set; }
    }
}
