//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DroneSite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Address = new HashSet<Order_Address>();
            this.Order_Line = new HashSet<Order_Line>();
        }
    
        public int id { get; set; }
        public int person_id { get; set; }
        public System.DateTime order_date { get; set; }
        public int duration { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<System.DateTime> date_returned { get; set; }
    
        public virtual ICollection<Order_Address> Order_Address { get; set; }
        public virtual ICollection<Order_Line> Order_Line { get; set; }
        public virtual Person Person { get; set; }
    }
}
